name: OWASP Dependency Check

on: [push, pull_request]

jobs:
  security-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "lts/*" # Use the latest stable (LTS) version

      - name: Install dependencies
        run: npm install

      - name: Run OWASP Dependency-Check
        uses: dependency-check/Dependency-Check_Action@main
        with:
          project: "prices-tracker-app-notes"
          path: "./"
          format: "HTML"
          out: "reports"
          args: "--failOnCVSS 7 --enableRetired"

      - name: Upload Report
        uses: actions/upload-artifact@v3
        with:
          name: dependency-check-report
          path: reports/dependency-check-report.html
          if-no-files-found: error
          if-exists: replace
